version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - ./data:/data
      - ./figures:/figures  # Map the figures directory
    environment:
      - POSTGRES_DB=gnews
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: gnews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

