version: '3.8'

services:
  app:
    image: py_app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py_app_cont
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db_pg_dev
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5