class ColNames: 
    country = 'country'
    risk_category_full_name='risk_category_full_name'
    commodity='commodity'
    lang='lang'
    prompt='prompt'
    data_source='data_source'
    url='url'
    title='title'
    published_date='published_date'
    publisher='publisher'
    download_state='download_state'
    upload_time='upload_time'
    article_clean_text='article_clean_text'
    manual_check_suggested = 'manual_check_suggested' 
    reason_for_manual_check = 'reason_for_manual_check' 
